# Generated by Django 6.0 on 2025-12-30 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='imageUrl',
            new_name='image_url',
        ),
    ]
